services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - ${NETWORK_NAME}

  circuirbreak:
    build:
      context: CircuitBreak/
      dockerfile: Dockerfile
    ports:
      - "5233:8080"
    environment:
      - ConnectionStrings__ElasticSearchConnection=${ELASTICSEARCH_HOST}

    networks:
      - ${NETWORK_NAME}


volumes:
  es_data:
    driver: local

networks:
  circuitbreak:
    driver: bridge
